"""The reviewed report a record can deliver, and how to find it again.

A template that says "press the button and we will send you the report" is a promise the
system has to be able to keep. It cannot keep it by rendering: there is no server-side PDF
renderer in this app - ``api/printing.py`` returns JSON and nothing imports ``get_pdf`` -
so the only bytes that can ever be sent are the ones the client generated and a human
reviewed. This module is where those bytes are put, and where they are found again.

Records are addressed as ``(doctype, name)``. Nothing here knows about Lab, Imaging, or any
template, and nothing here may learn: the clinic will add a radiology template and more
after it, and they have to work with no change to this file.

**Why a marker field and not a heuristic.** The obvious filter - newest attachment, or
newest ``.pdf`` - is wrong on this site's real data, not in theory. Lab and Imaging carry
over a thousand attachments between them (1047 as of 2026-09-03, and growing - this is
live intake, not a fixed count); nearly all are photos of paper results, and a handful are
PDFs a human uploaded that no one reviewed for sending. LAB-00538, the record behind the one
real button tap, has exactly one attachment and it is a ``.webp``. Either heuristic
sends the wrong file to a customer, which is the failure this whole change exists to
prevent. So a file is a reviewed report because something deliberately said so, and
``save_reviewed_report`` is the only thing that can say it.
"""

from __future__ import annotations

import base64

import frappe
from frappe import _
from frappe.core.doctype.file.utils import get_content_hash
from frappe.utils import cstr, now_datetime


# Custom Field on File, created by pet_app.patches.p1_26_reviewed_report_attachment.
# That patch is its only owner - it is deliberately absent from the fixture allow-list in
# hooks.py, which tests/test_fixture_allowlist.py enforces.
REVIEWED_REPORT_FIELD = "pet_app_reviewed_report"

# A PDF is a PDF because of its first five bytes, not because of its name. A filename is
# whatever the client typed; these bytes are what a PDF reader will actually see.
PDF_MAGIC = b"%PDF-"

# Meta's own cap for a document message. Refusing above it here means the system never
# stores a report it could not deliver. This is Meta's number, not a clinical judgement
# about how large a report should be - in practice the HTTP body limit binds long first.
META_DOCUMENT_LIMIT_BYTES = 100 * 1024 * 1024


def save_reviewed_report(doctype: str, name: str, *, content, file_name=None):
	"""Store one reviewed PDF against a record and mark it as the deliverable report.

	``content`` is the client's generated bytes, either raw ``bytes`` or the base64 /
	data-URL string a JSON request can carry. Decoding lives here rather than in the API
	layer so that there is exactly one place that turns a client payload into a stored
	report, and exactly one place that sets the marker.

	Re-sending identical bytes returns the file already stored rather than a second copy:
	the same reviewed document attached twice is one document. Different bytes always
	insert, because a re-reviewed report is a new report and ``newest_reviewed_report``
	has to see it.

	Callers own the permission decision - this writes with ``ignore_permissions`` once
	they have made it.
	"""
	content = _as_bytes(content)
	if not content:
		frappe.throw(_("The report file is empty."), title=_("Nothing to attach"))
	if not content.startswith(PDF_MAGIC):
		frappe.throw(
			_("The reviewed report must be a PDF. This file does not begin with %PDF-."),
			title=_("Not a PDF"),
		)
	_assert_readable_pdf(content)
	if len(content) > META_DOCUMENT_LIMIT_BYTES:
		frappe.throw(
			_("The reviewed report is {0} MB. WhatsApp cannot deliver a document over {1} MB.").format(
				round(len(content) / 1024 / 1024, 1), META_DOCUMENT_LIMIT_BYTES // 1024 // 1024
			),
			title=_("Too large to send"),
		)

	file_name = _pdf_file_name(file_name, name)
	existing = frappe.db.get_value(
		"File",
		{
			"attached_to_doctype": doctype,
			"attached_to_name": name,
			REVIEWED_REPORT_FIELD: 1,
			"content_hash": get_content_hash(content),
		},
		"name",
	)
	if existing:
		return frappe.get_doc("File", existing)

	# Private, unlike every attachment this site has today. A reviewed clinical report is
	# the guardian's record and a public file_url is a URL anyone can guess their way to.
	# Phase 4 sends it from a Guest webhook context, which is a permission question that
	# belongs to the send path, not to how the file is stored.
	return frappe.get_doc(
		{
			"doctype": "File",
			"file_name": file_name,
			"content": content,
			"attached_to_doctype": doctype,
			"attached_to_name": name,
			"is_private": 1,
			REVIEWED_REPORT_FIELD: 1,
		}
	).insert(ignore_permissions=True)


def newest_reviewed_report(doctype: str, name: str):
	"""The most recently attached reviewed report on one record, or None.

	Newest by ``creation``, filtered on the marker field - never on extension, and never
	on filename. The record's attachments are already a handful of rows once
	``attached_to_doctype`` and ``attached_to_name`` are fixed, so the marker is a filter
	over a tiny set and needs no index of its own.

	Reads with ``ignore_permissions``: the two callers are a staff send guard, which has
	already permission-checked the record, and the inbound webhook, which runs as Guest
	and answers to the guardian's own button tap. Whether this file may be sent is the
	caller's question; this function only answers which file it is.
	"""
	rows = frappe.get_all(
		"File",
		filters={
			"attached_to_doctype": doctype,
			"attached_to_name": name,
			REVIEWED_REPORT_FIELD: 1,
		},
		fields=["name", "file_name", "file_url", "is_private", "creation", "owner"],
		order_by="creation desc",
		limit_page_length=1,
		ignore_permissions=True,
	)
	return rows[0] if rows else None


def has_reviewed_report(doctype: str, name: str) -> bool:
	"""Whether a record has a reviewed report waiting. The Phase 3 send guard reads this."""
	if not doctype or not name:
		return False
	return bool(
		frappe.db.exists(
			"File",
			{
				"attached_to_doctype": doctype,
				"attached_to_name": name,
				REVIEWED_REPORT_FIELD: 1,
			},
		)
	)


def _assert_readable_pdf(content: bytes) -> None:
	"""Refuse a PDF that cannot be parsed, before File does it less clearly.

	frappe's File.check_content runs pdf_contains_js on every PDF, so a truncated or
	malformed one already fails - but as a raw pypdf ``startxref not found``, which tells
	the clinic nothing about what to do. Running the same check here turns it into a
	sentence, and keeps every rule about what may be stored as a report in one place.

	The JavaScript rejection underneath is frappe's and is deliberately left to it: it is
	a platform security rule, not a report rule, and restating it here would mean two
	copies to keep in step.
	"""
	from frappe.utils.pdf import pdf_contains_js

	try:
		pdf_contains_js(content)
	except frappe.ValidationError:
		raise
	except Exception:
		frappe.throw(
			_("This PDF could not be read. It may be truncated or corrupted - regenerate it and try again."),
			title=_("Unreadable PDF"),
		)


def _as_bytes(content) -> bytes:
	"""Raw bytes, a base64 string, or a data URL - all end up as bytes."""
	if isinstance(content, bytes):
		return content
	if isinstance(content, bytearray):
		return bytes(content)
	value = cstr(content).strip()
	if not value:
		return b""
	if "," in value and value.split(",", 1)[0].startswith("data:"):
		value = value.split(",", 1)[1]
	try:
		return base64.b64decode(value, validate=False)
	except Exception:
		frappe.throw(_("The report file could not be decoded."), title=_("Unreadable upload"))


def _pdf_file_name(file_name, record_name: str) -> str:
	"""A safe filename ending in .pdf.

	The customer sees this string in WhatsApp, and ``inbox._media_type`` reads its
	extension to decide the message type, so an extensionless name is both worse to look
	at and one refactor away from being sent as the wrong kind of media. Path separators
	are stripped because a filename from a client is untrusted input.
	"""
	candidate = cstr(file_name).strip().replace("\\", "/").rsplit("/", 1)[-1]
	candidate = candidate or f"{cstr(record_name).strip()}.pdf"
	if not candidate.lower().endswith(".pdf"):
		candidate = f"{candidate}.pdf"
	return candidate


# ---------------------------------------------------------------------------
# delivering the report when the customer taps the button
# ---------------------------------------------------------------------------

# A repeat tap re-sends: the customer pressed a button that promised a report, so they
# get one. This guards only against the same tap being answered twice - a Meta webhook
# redelivery, or a double press - and a minute is wide enough to cover both while staying
# far below any interval a person would call "asking again".
DOUBLE_FIRE_SECONDS = 60


def enqueue_reply_report_delivery(message, conversation):
	"""Queue the report a tap was promised, if this reply is one that was promised one.

	Called from the inbound webhook. Everything expensive happens in the background job:
	the webhook must not make an outbound HTTP call inline, because dedup writes
	processed=1 only after _apply_event returns (webhook.py:34-43), so a slow send would
	let Meta redeliver into the unique constraint on the stored event row. This would be
	the first inbound path making such a call, so the rule gets stated rather than
	assumed.

	enqueue_after_commit means a rolled-back webhook sends nothing. The deduplicating
	job_id catches a redelivery that is already queued; the job re-checks against the
	database anyway, because a job id only exists while its job does.
	"""
	target = resolve_reply_report(message)
	if not target:
		return None

	frappe.enqueue(
		"pet_app.notifications.reports.send_reply_report",
		queue="short",
		enqueue_after_commit=True,
		job_id=_delivery_job_id(conversation.name, target["source_doctype"], target["source_name"]),
		deduplicate=True,
		conversation_name=conversation.name,
		file_name=target["file"]["name"],
		inbound_message=message.name,
	)
	return target


def resolve_reply_report(message):
	"""What a reply should be answered with, or None. A pure lookup - it sends nothing.

	The chain, all of it indexed reads:

	    inbound.replied_to_message   the wamid Meta sent as message.context.id (p1_25)
	      -> outbound message        which carries source_doctype / source_name already
	      -> its notification queue  which names the Meta template that was sent
	      -> the mirror row          which says whether that template promised a report

	Nothing here names a template or a doctype. A radiology template promising an Imaging
	report resolves through exactly these four reads with nothing added.
	"""
	replied_to = message.get("replied_to_message")
	if not replied_to:
		return None

	outbound = frappe.db.get_value(
		"Pet App WhatsApp Message",
		replied_to,
		["name", "direction", "notification_queue", "source_doctype", "source_name"],
		as_dict=True,
	)
	# A guardian can quote their own earlier message; that is a reply to us about
	# nothing we promised.
	if not outbound or outbound.direction != "Outbound" or not outbound.notification_queue:
		return None
	if not outbound.source_doctype or not outbound.source_name:
		return None

	meta_template = frappe.db.get_value(
		"Pet App Notification Queue", outbound.notification_queue, "meta_template"
	)
	if not meta_template:
		return None

	from pet_app.notifications.meta_templates import promises_reviewed_report

	if not promises_reviewed_report(meta_template):
		return None

	report = newest_reviewed_report(outbound.source_doctype, outbound.source_name)
	if not report:
		# Phase 3 refuses a send with no report attached, so reaching here means the
		# report was removed between the promise and the tap. Worth a line in the log:
		# a guardian is waiting for something nobody can send them.
		frappe.logger("pet_app.whatsapp_report").warning(
			"Tap on %s promised a report for %s %s, and none is attached.",
			outbound.name,
			outbound.source_doctype,
			outbound.source_name,
		)
		return None

	return {
		"outbound_message": outbound.name,
		"source_doctype": outbound.source_doctype,
		"source_name": outbound.source_name,
		"meta_template": meta_template,
		"file": report,
	}


def send_reply_report(conversation_name, file_name, inbound_message=None):
	"""The background job. Sends the stored file, and never regenerates it.

	Runs as Administrator because the webhook that scheduled it is allow_guest, and
	frappe.enqueue carries the calling session's user with no way to override it - so
	without this the job runs as Guest and send_conversation_message's read permission
	check on a now-private file fails, which is the silent no-op this whole change
	exists to remove. The actor genuinely is the system: no person is at a keyboard, and
	the authorisation is the guardian's own tap.

	Consent and rate limits are deliberately still enforced - they live inside
	send_conversation_message and a system actor is not a reason to skip them.
	"""
	frappe.set_user("Administrator")

	from pet_app.notifications.inbox import notify_inbox_users, send_conversation_message

	if _already_sent_within_double_fire_window(conversation_name, file_name):
		frappe.logger("pet_app.whatsapp_report").info(
			"Skipping report %s to %s: an identical send is less than %ss old.",
			file_name,
			conversation_name,
			DOUBLE_FIRE_SECONDS,
		)
		return None

	try:
		return send_conversation_message(conversation_name, file_name=file_name)
	except Exception:
		# A guardian has been told a report is coming and it is not. That cannot be a
		# line in the error log nobody reads, so it also lands in the inbox where staff
		# are already looking at this conversation.
		frappe.log_error(
			title="WhatsApp reviewed report delivery failed",
			message=(
				f"conversation={conversation_name} file={file_name} "
				f"inbound_message={inbound_message}\n\n{frappe.get_traceback()}"
			),
		)
		conversation = frappe.get_doc("Pet App WhatsApp Conversation", conversation_name)
		message = (
			frappe.get_doc("Pet App WhatsApp Message", inbound_message)
			if inbound_message and frappe.db.exists("Pet App WhatsApp Message", inbound_message)
			else None
		)
		if message:
			notify_inbox_users(
				conversation,
				message,
				subject=_("A promised report could not be sent - send it manually"),
			)
		raise


def _already_sent_within_double_fire_window(conversation_name, file_name) -> bool:
	"""Whether this exact file went to this conversation moments ago.

	The authoritative guard, checked in the job rather than at enqueue time: two webhook
	deliveries racing can both pass the queue's dedup before either has enqueued, and a
	job id stops existing once its job finishes.

	Scoped to this file rather than to the record, so a corrected report attached
	seconds after the first one still goes out - it is a different file, and the customer
	is owed the corrected one.
	"""
	from frappe.utils import add_to_date

	return bool(
		frappe.db.exists(
			"Pet App WhatsApp Message",
			{
				"conversation": conversation_name,
				"direction": "Outbound",
				"file": file_name,
				"message_at": [">=", add_to_date(now_datetime(), seconds=-DOUBLE_FIRE_SECONDS)],
			},
		)
	)


def _delivery_job_id(conversation_name, source_doctype, source_name) -> str:
	"""One job per conversation, record and minute.

	The minute bucket is what makes a repeat tap a minute later a real re-send rather
	than a job id collision, which is the agreed behaviour: the customer pressed a button
	that promised a report, so they get one.
	"""
	minute = now_datetime().strftime("%Y%m%d%H%M")
	return f"pet-app-reply-report:{conversation_name}:{source_doctype}:{source_name}:{minute}"
