from __future__ import annotations

import re

import frappe
from frappe import _
from frappe.model.document import Document
from frappe.utils import cint, cstr


class MobileHomeFilter(Document):
	def autoname(self):
		self.filter_key = _clean_key(self.filter_key or self.name)
		self.name = self.filter_key

	def validate(self):
		self.filter_key = _clean_key(self.filter_key or self.name)
		if not self.filter_key:
			frappe.throw(_("Filter Key is required."))
		if self.filter_key == "all":
			frappe.throw(_("The All filter is generated by the backend."))
		self.label_en = cstr(self.label_en).strip()
		self.label_ar = cstr(self.label_ar).strip()
		if not self.label_en or not self.label_ar:
			frappe.throw(_("English and Arabic filter labels are required."))
		self.display_order = cint(self.display_order) or 10


def _clean_key(value) -> str:
	value = cstr(value).strip().lower()
	value = re.sub(r"[^a-z0-9]+", "-", value).strip("-")
	return value
